### PR TITLE
added flashlight-fish

### PR DESCRIPTION
**Pull request by terraroush**
i added a flashlight fish named gollum

### CODE REVIEW

**Comment by blaker814** [comment]
Loved the LOTR references! I might consider capitalizing everything in the properties since that is how the rest of the cards have done it. Also, there was one div that wasn't quite lined up right on line 109

**Comment by HanakoH** [comment]
Looks great! I agree with Rick's notes and also, for continuity, thought it might be good to spell out inches to keep with the rest of the cards.

**Comment by ste163** [comment]
Love it!

**Review by bloges56 — APPROVED** [review]
Looks good to me! 👍

**Comment by terraroush** [comment]
> Loved the LOTR references! I might consider capitalizing everything in the properties since that is how the rest of the cards have done it. Also, there was one div that wasn't quite lined up right on line 109

**Pull request closed without merging**
