### PR TITLE
created additional css files for import

### PR DESCRIPTION
**Pull request by brendalong**
Make sure the css for the header shows up and the aside.

### CODE REVIEW

**Comment by jisie** [comment]
Looks good 👍

**Review by jisie — APPROVED** [review]

**Comment by Patchrik** [comment]
Also looks good 👍 - Hi class 👋

**Comment by cArel116** [comment]
*Test* Great explanation, Jisie!

**Comment by HanakoH** [comment]
Just checked it out! 💯

**Comment by TessaSoftEng** [comment]
Checked it out. Looks good.

**Review by TAPinson — APPROVED** [review]
Very nice!

**Pull request merged**
